package analyzer;

import model.Packet;
import java.util.ArrayList;
import java.util.HashMap;

public class TrafficAnalyzer {

    // Store: IP Address -> Number of Packets
    private HashMap<String, Integer> packetCountMap;
    private HashMap<String, Integer> destinationPacketCountMap;

    public TrafficAnalyzer() {
        this.packetCountMap = new HashMap<>();
        this.destinationPacketCountMap = new HashMap<>();
    }

    /**
     * Method to analyze the generated packets and group them by Source and Destination IP
     * @param packets ArrayList of Packet objects generated by the simulator
     */
    public void analyzeTraffic(ArrayList<Packet> packets) {
        packetCountMap.clear(); // Clear previous data
        destinationPacketCountMap.clear();

        // Loop through all packets
        for (Packet packet : packets) {
            String sourceIP = packet.getSourceIP();
            String destinationIP = packet.getDestinationIP();

            // Count Packets Per Source IP
            packetCountMap.put(sourceIP, packetCountMap.getOrDefault(sourceIP, 0) + 1);

            // Count Packets Per Destination IP
            destinationPacketCountMap.put(destinationIP, destinationPacketCountMap.getOrDefault(destinationIP, 0) + 1);
        }
    }

    /**
     * Method to print the traffic statistics report
     */
    public void printReport() {
        System.out.println("--- Traffic Analysis Report ---");

        System.out.println("\nSource IP Distribution:");
        for (String ip : packetCountMap.keySet()) {
            int count = packetCountMap.get(ip);
            System.out.println(ip + " -> " + count + " packets");
        }

        System.out.println("\nDestination IP Distribution:");
        for (String ip : destinationPacketCountMap.keySet()) {
            int count = destinationPacketCountMap.get(ip);
            System.out.println(ip + " -> " + count + " packets");
        }
        
        System.out.println();
    }

    /**
     * Method to get the HashMap statistics so the AttackDetector can use it
     * @return HashMap containing IP Address and their respective packet counts
     */
    public HashMap<String, Integer> getPacketCountMap() {
        return packetCountMap;
    }

    public HashMap<String, Integer> getDestinationPacketCountMap() {
        return destinationPacketCountMap;
    }

    /**
     * Method to find and return the IP that sent the most packets
     * @return Most active Source IP Address
     */
    public String getMostActiveIP() {
        String mostActiveIP = null;
        int maxCount = 0;

        for (String ip : packetCountMap.keySet()) {
            int currentCount = packetCountMap.get(ip);
            if (currentCount > maxCount) {
                maxCount = currentCount;
                mostActiveIP = ip;
            }
        }

        if (mostActiveIP != null) {
            System.out.println("Most Active Source IP: " + mostActiveIP);
        }

        return mostActiveIP;
    }

    /**
     * Method to find and return the IP that received the most packets
     * @return Most targeted Destination IP Address
     */
    public String getVictimIP() {
        String victimIP = null;
        int maxCount = 0;

        for (String ip : destinationPacketCountMap.keySet()) {
            int currentCount = destinationPacketCountMap.get(ip);
            if (currentCount > maxCount) {
                maxCount = currentCount;
                victimIP = ip;
            }
        }

        if (victimIP != null) {
            System.out.println("Victim IP (Highest Traffic): " + victimIP);
        }

        return victimIP;
    }
}
