package analyzer;

import model.Packet;
import java.util.ArrayList;
import java.util.HashMap;

public class TrafficAnalyzer {

    // Store: IP Address -> Number of Packets
    private HashMap<String, Integer> packetCountMap;

    public TrafficAnalyzer() {
        this.packetCountMap = new HashMap<>();
    }

    /**
     * Method to analyze the generated packets and group them by Source IP
     * @param packets ArrayList of Packet objects generated by the simulator
     */
    public void analyzeTraffic(ArrayList<Packet> packets) {
        packetCountMap.clear(); // Clear previous data

        // Loop through all packets
        for (Packet packet : packets) {
            String sourceIP = packet.getSourceIP();

            // Count Packets Per Source IP
            if (packetCountMap.containsKey(sourceIP)) {
                // IP already exists, increment its count
                int count = packetCountMap.get(sourceIP);
                packetCountMap.put(sourceIP, count + 1);
            } else {
                // New IP encountered, count is 1
                packetCountMap.put(sourceIP, 1);
            }
        }
    }

    /**
     * Method to print the traffic statistics report
     */
    public void printReport() {
        System.out.println("--- Traffic Analysis Report ---");

        // Loop through the HashMap to print each IP and its packet count
        for (String ip : packetCountMap.keySet()) {
            int count = packetCountMap.get(ip);
            System.out.println(ip + " -> " + count + " packets");
        }
        
        System.out.println();
    }

    /**
     * Method to get the HashMap statistics so the AttackDetector can use it
     * @return HashMap containing IP Address and their respective packet counts
     */
    public HashMap<String, Integer> getPacketCountMap() {
        return packetCountMap;
    }

    /**
     * Method to find and return the IP that sent the most packets
     * @return Most active Source IP Address
     */
    public String getMostActiveIP() {
        String mostActiveIP = null;
        int maxCount = 0;

        // Loop through the HashMap to find the IP with maximum packets
        for (String ip : packetCountMap.keySet()) {
            int currentCount = packetCountMap.get(ip);
            
            if (currentCount > maxCount) {
                maxCount = currentCount;
                mostActiveIP = ip;
            }
        }

        // Print IP sending maximum packets
        if (mostActiveIP != null) {
            System.out.println("Most Active IP: " + mostActiveIP);
        }

        return mostActiveIP;
    }
}
